### ISSUE TITLE
Toshiba schematic is missing Resistor values

### ISSUE THREAD

**Issue by imtoanle** [peng-zhihui/HDMI-PI#18]
First. Sorry because i using English here.

I'm trying to work with Toshiba solution. But i couldn't find exactly value of R23, R25 and R29.
I am not familiar with electronics to understand all thing here.

<img width="901" alt="Screen Shot 2020-12-04 at 16 13 02" src="https://user-images.githubusercontent.com/4002252/101145495-713a6980-364c-11eb-8266-2daeaf6882e8.png">
<img width="653" alt="Screen Shot 2020-12-04 at 16 13 34" src="https://user-images.githubusercontent.com/4002252/101145503-74355a00-364c-11eb-9613-c2bd46a782b1.png">

Could anyone help me here.

Thanks

**Comment by tansirui** [comment]
> First. Sorry because i using English here.
> 
> I'm trying to work with Toshiba solution. But i couldn't find exactly value of R23, R25 and R29.
> I am not familiar with electronics to understand all thing here.
> 
> <img alt="Screen Shot 2020-12-04 at 16 13 02" width="901" src="https://user-images.githubusercontent.com/4002252/101145495-713a6980-364c-11eb-8266-2daeaf6882e8.png">
> 
> <img alt="Screen Shot 2020-12-04 at 16 13 34" width="653" src="https://user-images.githubusercontent.com/4002252/101145503-74355a00-364c-11eb-9613-c2bd46a782b1.png">
> 
> Could anyone help me here.
> 
> Thanks

Nc means not connected, so R25, R29 can be unwelded. R23 uses 0 ohm resistor to short circuit.

**Comment by imtoanle** [comment]
I make sense. Thank @tansirui so much
