### ISSUE TITLE
关于我创建的一个技术交流群

### ISSUE THREAD

**Issue by kumonohayaku** [peng-zhihui/HDMI-PI#24]
我创了个技术交流群，欢迎dalao们进来讨论，非拼车群，主要交流如何自己驱动任意液晶屏和驱动板设计开发等等，本人也对如何驱动mipi液晶不太了解，目前正在调试开发中，目标是驱动一个6.8寸1080的屏幕。
群号：879256453

**Comment by kumonohayaku** [comment]
![IMG_20210308_153426](https://user-images.githubusercontent.com/76272918/110729537-e031ea80-8259-11eb-85ed-e73d0520c5e1.jpg)
2021-3-8成功调试成功，感谢各位大佬们，最后驱动程序将整合在https://github.com/ylj2000/HDMI_To_MIPI

的项目里。

**Comment by peng-zhihui** [comment]
很棒，感谢分享~
