### ISSUE TITLE
关于屏幕、DSI和树莓派

### ISSUE THREAD

**Issue by nineandthreequarters** [peng-zhihui/HDMI-PI#6]
> 树莓派有 **_DSI_** +手机屏幕用 **_DSI_**  ==> 树莓派可以直接连手机拆机屏幕进行显示
>- [ ] **这条假设成立吗？**

**Comment by tansirui** [comment]
应该不可以直接用，单单接口就得转接。

**Comment by 12101111** [comment]
https://github.com/anholt/linux/wiki/VC4-display-support
https://github.com/anholt/linux/wiki/Raspberry-Pi-and-other-MIPI-DSI-display-panels
https://www.cnblogs.com/B1ue/p/10334900.html
