### ISSUE TITLE
关于所支持的屏幕分辨率

### ISSUE THREAD

**Issue by JYH851** [peng-zhihui/HDMI-PI#8]
在固件中我看到那个固件的标题中写的是800*1280，我想知道是这个固件只能支持这个分辨率吗

**Comment by peng-zhihui** [comment]
不只是分辨率，驱动屏幕的核心是对接屏幕控制器，每一块屏幕都不一样的，需要针对特定屏幕修改固件（虽然同一型号的控制器修改量很小）



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: JYH851 <notifications@github.com&gt;
发送时间: 2020年11月29日 17:29
收件人: peng-zhihui/HDMI-PI <HDMI-PI@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[peng-zhihui/HDMI-PI] 关于所支持的屏幕分辨率 (#8)





 
在固件中我看到那个固件的标题中写的是800*1280，我想知道是这个固件只能支持这个分辨率吗

**Comment by 0x01x0** [comment]
我有个报废iPad 能不能上？
